#!/bin/bash

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | tee /etc/apt/sources.list.d/mono-xamarin.list

apt-get update

apt-get install -y \
        autoconf \
        automake \
        g++ \
        git \
        gksu \
        gtk-sharp2 \
        libgtk2.0-dev \
        libtool \
        mono-complete \
        python2.7 \
        realpath \
        screen \
        uml-utilities
