#!/bin/bash

DEBIAN_FRONTEND=noninteractive apt-get install -y gnupg


if [[ -v http_proxy ]]; then
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --keyserver-options http-proxy=$http_proxy --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
else
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
fi

echo "deb http://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-xamarin.list

apt-get update

DEBIAN_FRONTEND=noninteractive apt-get install -y \
        autoconf \
        automake \
        g++ \
        git \
        gtk-sharp2 \
        libgtk2.0-dev \
        libtool \
        mono-complete \
        python2.7 \
        screen \
        uml-utilities
